import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.demoblaze.com/');
  await page.getByRole('link', { name: 'Nokia lumia' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('link', { name: 'Add to cart' }).click();
  await page.getByRole('link', { name: 'Cart', exact: true }).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
  await page.getByRole('textbox', { name: 'Total: 820 Name:' }).click();
  await page.getByRole('textbox', { name: 'Total: 820 Name:' }).fill('angelo dayan');
  await page.getByRole('textbox', { name: 'Country:' }).click();
  await page.getByRole('textbox', { name: 'Country:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Country:' }).fill('A');
  await page.getByRole('textbox', { name: 'Country:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Country:' }).fill('Argentina');
  await page.getByRole('textbox', { name: 'City:' }).click();
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('B');
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('Buenos ');
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('Buenos A');
  await page.getByRole('textbox', { name: 'City:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'City:' }).fill('Buenos Aires');
  await page.getByRole('textbox', { name: 'Credit card:' }).click();
  await page.getByRole('textbox', { name: 'Credit card:' }).fill('5428368892459076');
  await page.getByRole('textbox', { name: 'Month:' }).click();
  await page.getByRole('textbox', { name: 'Month:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Month:' }).fill('F');
  await page.getByRole('textbox', { name: 'Month:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Month:' }).fill('Febrero');
  await page.getByRole('textbox', { name: 'Year:' }).click();
  await page.getByRole('textbox', { name: 'Year:' }).fill('2026');
  await page.getByRole('button' , { name: 'Purchase' }).click();
  await expect(page.getByText('Thank you for your purchase!')).toBeVisible();
  await page.getByRole('button', { name: 'OK' }).click();
});